
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Aug 19 21:09:14 CEST 2019
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RIGHT_BRACKET = 42;
  public static final int INCREMENT = 34;
  public static final int CHAR = 47;
  public static final int CONST = 8;
  public static final int PERIOD = 38;
  public static final int NOT_EQUAL = 26;
  public static final int SEMI = 36;
  public static final int GREATER = 27;
  public static final int CONTINUE = 18;
  public static final int INTERFACE = 5;
  public static final int DECREMENT = 35;
  public static final int LESS = 29;
  public static final int FOR = 15;
  public static final int MINUS = 21;
  public static final int AND = 31;
  public static final int LEFT_PARENTHES = 39;
  public static final int OR = 32;
  public static final int BOOL = 48;
  public static final int LEFT_BRACE = 43;
  public static final int COMMA = 37;
  public static final int CLASS = 4;
  public static final int DIV = 23;
  public static final int LESS_EQUAL = 30;
  public static final int PLUS = 20;
  public static final int ASSIGN = 33;
  public static final int IF = 9;
  public static final int THIS = 19;
  public static final int EOF = 0;
  public static final int RETURN = 13;
  public static final int EQUAL = 25;
  public static final int GREATER_EQUAL = 28;
  public static final int NEW = 10;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 22;
  public static final int VALUES = 45;
  public static final int RIGHT_BRACE = 44;
  public static final int NUMBER = 49;
  public static final int MOD = 24;
  public static final int IDENT = 46;
  public static final int BREAK = 3;
  public static final int VOID = 14;
  public static final int ELSE = 7;
  public static final int ENUM = 6;
  public static final int READ = 12;
  public static final int RIGHT_PARENTHES = 40;
  public static final int EXTENDS = 16;
  public static final int IMPLEMENTS = 17;
  public static final int LEFT_BRACKET = 41;
  public static final int PRINT = 11;
}

